package cc

const moduleFileTpl = `// Code generated by protoc-gen-validate
// source: {{ .InputPath }}
// DO NOT EDIT!!!

#include "{{ output .File ".validate.h" }}"

#include <algorithm>
#include <string>
#include <unordered_set>
#include <vector>

#include <google/protobuf/message.h>
#include <google/protobuf/util/time_util.h>

#include "pgv/constants.hpp"
#include "pgv/validate.hpp"

{{ $include_custom := true }}
{{- range .AllMessages -}}
{{- if and (custom_validate .) ($include_custom) -}}
{{- $include_custom = false }}
// Custom registration for validation of {{ class . }} specified by the protobuf schema.
// The included file should create a global object that register the user defined validation function.
// Example:
// clang-format off
// namespace { pgv::Validator<{{ class . }}> {{ staticVarName . }}(static_cast<bool(*)(const google::protobuf::Message&, const {{ class .}}&, pgv::ValidationLog*)>({{ package .}}::validate)); }
// clang-format on
#include "{{ output .File ".custom_validate_init.cpp" }}"
{{- end -}}
{{ end }}

namespace pgv {

namespace protobuf = google::protobuf;
namespace protobuf_wkt = google::protobuf;

namespace {
{{ range .AllMessages }}
{{- if not (ignored .) -}}
{{- if not (disabled .) -}}
{{- if not (custom_validate .) -}}

pgv::Validator<{{ class . }}> {{ staticVarName . }}(static_cast<bool(*)(const google::protobuf::Message&, const {{ class .}}&, pgv::ValidationLog*)>({{ package .}}::validate));

{{- end -}}
{{- end -}}
{{ end }}
{{ end }}
} // namespace validate
} // namespace pgv

{{ range .Package.ProtoName.SplitOnDot }}
namespace {{ . }} {
{{- end }}

using namespace pgv::constants;

{{ range .AllMessages }}
	{{- template "msg" . }}
{{ end }}

{{ range .Package.ProtoName.SplitOnDot -}}
} // namespace
{{ end }}
`

const headerFileTpl = `// Code generated by protoc-gen-validate
// source: {{ .InputPath }}
// DO NOT EDIT!!!

#pragma once

#include "pgv/validate_detail.hpp"
#include "{{ output .File ".h" }}"

{{ range .Package.ProtoName.SplitOnDot }}
namespace {{ . }} {
{{- end }}

{{ range .AllMessages }}
	{{- template "decl" . }}
{{ end }}

{{ range .Package.ProtoName.SplitOnDot -}}
} // namespace {{ . }}
{{ end }}

namespace pgv {
{{ range .AllMessages }}
{{- if not (ignored .) -}}
{{- if not (disabled .) -}}
{{- if not (custom_validate .) -}}
/// @ref {{ class . }}
[[nodiscard]] inline bool validate(const {{ class . }}& m, pgv::ValidationLog* err = nullptr) {
    return {{ package . }}::validate(m, err);
}
{{- else -}}
// custom validator for message {{ class . }}
{{ end }}
{{- end -}}
{{ end }}
{{ end }}
}
`
